name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Copy env vars, create enviroment, and run program
        run: |
          echo "{CHROME_DRIVER}={chrome-linux}" >> $GITHUB_ENV
          cp .env.example .env
          pip install virtualenv
          pip install pipenv
          virtualenv .venv
          pipenv install --ignore-pipfile
          pipenv run start
