name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Copy env vars, create enviroment, and run program
        run: |
          chmod 755 drivers/chrome-linux
          cp .env.example .env
          sed -i 's/CHROME_DRIVER=chrome-windows/CHROME_DRIVER=chrome-linux/' .env
          pip install virtualenv
          pip install pipenv
          virtualenv .venv
          pipenv install --ignore-pipfile
          pipenv run start
