name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Copy env vars, create enviroment, and run program
        run: |
          cp .env.example .env
          sed -i 's/CHROME_DRIVER=chrome-windows/CHROME_DRIVER=chrome-linux/' .env
          pip install virtualenv
          sudo pip install pipenv
          virtualenv .venv
          pipenv install --ignore-pipfile
          sudo pipenv run start
